services:
  users-api:
    image: oven/bun:alpine
    container_name: users-api
    command: ["bun", "run", "--hot", "index.ts"]
    env_file: .env
    ports:
      - 3001:3001
    working_dir: /var/www/html
    volumes:
      - ./users-api:/var/www/html
    networks:
      - default

  events-api:
    image: php:8.3-fpm-alpine
    container_name: events-api
    build: .
    command: ["php", "-S", "0.0.0.0:3002", "-t", "/var/www/html/public"]
    env_file: .env
    ports:
      - 3002:3002
    working_dir: /var/www/html
    volumes:
      - ./events-api:/var/www/html
    networks:
      - default

  emails-api:
    image: oven/bun:alpine
    container_name: emails-api
    command: ["bun", "run", "--hot", "index.ts"]
    env_file: .env
    ports:
      - 3004:3004
    working_dir: /var/www/html
    volumes:
      - ./emails-api:/var/www/html
    networks:
      - default
  
  certificates-api:
    image: oven/bun:alpine
    container_name: certificates-api
    command: ["bun", "run", "--hot", "index.ts"]
    env_file: .env
    ports:
      - 3005:3005
    working_dir: /var/www/html
    volumes:
      - ./certificates-api:/var/www/html
    networks:
      - default

  app-gateway:
    image: oven/bun:alpine
    container_name: app-gateway
    command: ["bun", "run", "--hot", "index.ts"]
    env_file: .env
    ports:
      - 3000:3000
    working_dir: /var/www/html
    volumes:
      - ./app-gateway:/var/www/html
    networks:
      - default

networks:
  default:
    name: network-sistema
    driver: bridge